version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:latest
    volumes:
      - ./devnet:/data
    environment:
      - CARDANO_BLOCK_PRODUCER=true
      - CARDANO_SOCKET_PATH=/data/ipc/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/data/ipc/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/data/cardano-node.json"
      , "--topology", "/data/topology.json"
      , "--database-path", "/data/db"
      , "--shelley-operational-certificate", "/data/credentials/opcert1.cert"
      , "--shelley-kes-key", "/data/credentials/delegate1.kes.skey"
      , "--shelley-vrf-key", "/data/credentials/delegate1.vrf.skey"
      ]

  hydra-node-alice:
    image: ghcr.io/input-output-hk/hydra-node@sha256:6ff08464a426fe2e6e4c7b4c091cc61cae10efa28276adf0914f2d33bd45742a
    build:
      context: ../
      target: hydra-node
    volumes:
      - ./keys:/keys:ro
      - ./devnet/credentials:/credentials:ro
      - ./devnet/ipc:/ipc
      - ./devnet:/config
    ports:
      - "4001:4001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.10"
      , "--monitoring-port", "6001"
      , "--peer", "hydra-node-bob:5001"
      , "--hydra-signing-key", "/keys/alice.sk"
      , "--hydra-verification-key", "/keys/bob.vk"
      , "--cardano-signing-key", "/credentials/alice.sk"
      , "--cardano-verification-key", "/credentials/bob.vk"
      , "--ledger-genesis", "/config/genesis-shelley.json"
      , "--ledger-protocol-parameters", "/config/protocol-parameters.json"
      , "--network-id", "42"
      , "--node-socket", "/ipc/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-bob:
    image: ghcr.io/input-output-hk/hydra-node@sha256:6ff08464a426fe2e6e4c7b4c091cc61cae10efa28276adf0914f2d33bd45742a
    build:
      context: ../
      target: hydra-node
    volumes:
      - ./keys:/keys:ro
      - ./devnet/credentials:/credentials:ro
      - ./devnet/ipc:/ipc
      - ./devnet:/config
    ports:
      - "4002:4001"
    command:
      [ "--node-id", "2"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.20"
      , "--monitoring-port", "6001"
      , "--peer", "hydra-node-alice:5001"
      , "--hydra-signing-key", "/keys/bob.sk"
      , "--hydra-verification-key", "/keys/alice.vk"
      , "--cardano-signing-key", "/credentials/bob.sk"
      , "--cardano-verification-key", "/credentials/alice.vk"
      , "--ledger-genesis", "/config/genesis-shelley.json"
      , "--ledger-protocol-parameters", "/config/protocol-parameters.json"
      , "--network-id", "42"
      , "--node-socket", "/ipc/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always

networks:
  hydra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
