version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.35.2}
    volumes:
      - ./devnet:/data
      - /home/mitch/cardano/node/testnet:/node
    environment:
      - CARDANO_SOCKET_PATH=/node/node.socket # used by cardano-node
      - CARDANO_NODE_SOCKET_PATH=/node/node.socket # used by cardano-cli
    command:
      [ "run"
      , "--config", "/data/testnet-config.json"
      , "--topology", "/data/testnet-topology.json"
      , "--database-path", "/node/db"
      , "--socket-path", "/node/node.socket"
      ]

  hydra-node-alice:
    image: hydra-node-vasil:latest
    volumes:
      - ./keys:/keys:ro
      - ./devnet/credentials:/credentials:ro
      - ./devnet/ipc:/ipc
      - ./devnet:/config
      - /home/mitch/cardano/node/testnet:/node
    ports:
      - "4001:4001"
    command:
      [ "--node-id", "1"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.10"
      , "--monitoring-port", "6001"
      , "--peer", "hydra-node-bob:5001"
      , "--hydra-signing-key", "/keys/alice.sk"
      , "--hydra-verification-key", "/keys/bob.vk"
      , "--cardano-signing-key", "/credentials/alice.sk"
      , "--cardano-verification-key", "/credentials/bob.vk"
      , "--ledger-genesis", "/config/testnet-shelley-genesis.json"
      , "--ledger-protocol-parameters", "/node/protocol.json"
      , "--network-id", "1097911063"
      , "--node-socket", "/node/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.10
    restart: always

  hydra-node-bob:
    image: hydra-node-vasil:latest
    volumes:
      - ./keys:/keys:ro
      - ./devnet/credentials:/credentials:ro
      - ./devnet/ipc:/ipc
      - ./devnet:/config
      - /home/mitch/cardano/node/testnet:/node
    ports:
      - "4002:4001"
    command:
      [ "--node-id", "2"
      , "--api-host", "0.0.0.0"
      , "--host", "172.16.238.20"
      , "--monitoring-port", "6001"
      , "--peer", "hydra-node-alice:5001"
      , "--hydra-signing-key", "/keys/bob.sk"
      , "--hydra-verification-key", "/keys/alice.vk"
      , "--cardano-signing-key", "/credentials/bob.sk"
      , "--cardano-verification-key", "/credentials/alice.vk"
      , "--ledger-genesis", "/config/testnet-shelley-genesis.json"
      , "--ledger-protocol-parameters", "/node/protocol.json"
      , "--network-id", "1097911063"
      , "--node-socket", "/node/node.socket"
      ]
    networks:
      hydra_net:
        ipv4_address: 172.16.238.20
    restart: always

networks:
  hydra_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
