#!/bin/sh -e

cd "$(dirname "$(realpath "$0")")"

docker-compose down
./reset-devnet.sh
docker-compose up -d
echo -n 'Waiting for the node socket ..'
while ! [ -S devnet/ipc/node.socket ]
do
  echo -n .
  sleep 0.1
done
echo '. done'
sudo chown -Rv $(id -u):$(id -g) devnet/ipc
docker-compose exec cardano-node bash -c 'cd /data; . ./init.sh'
